const videoCategories = [
  "Music",
  "Education",
  "Entertainment",
  "Gaming",
  "Sports",
  "News",
  "Comedy",
  "How-to/Tutorials",
  "Vlogs",
  "Travel",
  "Science and Technology",
  "Movies/Films",
  "Animation",
  "Fitness",
  "Food/Cooking",
  "Fashion/Beauty",
  "Documentaries",
  "Pets/Animals",
  "DIY (Do It Yourself)",
  "Automotive",
  "Drama",
  "Cybersecurity",
  "Stories",
  "Others",
];
videoCategories.sort();
export default videoCategories;
